services:
  backend:
    build:
      context: ./poligonos
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: Poligonos-backend

  frontend:
    build:
      context: ./poligonosfront
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: Poligonos-frontend
    depends_on:
      - backend